### DISCUSSION TITLE
how to create multi blogs?

### DISCUSSION THREAD

**Discussion by DamonsJ** [george-gca/multi-language-al-folio#46] [Q&A]
here is what i have done:

1. fork this  repo [multi-language-al-folio](https://github.com/george-gca/multi-language-al-folio)
2. delete news.md projects.md  publications.md teaching.md repositories.md in _pages folder
3. duplicate  blog.md  as programming.md
4. changing programming.md 
- frontmatter
```
           ---
      layout: default
      permalink: /programming/
      title: programming
      nav: true
      nav_order: 4
      pagination:
        enabled: true
        collection: programming
        permalink: /page/:num/
        per_page: 5
        sort_field: date
        sort_reverse: true
        trail:
          before: 1 # The number of links before the current page
          after: 3 # The number of links after the current page
      ---
```
- replace blog_name  to programming_name and blog_description to  programming_description
- replace display_tags to programming_tags
- replace site.posts to site.programming

5. duplicate _posts folder as _programming folder
6. change _config.yml

```
programming_name: programming # programming_name will be displayed in your programming page
programming_description: a simple whitespace theme for programming

collections:
  books:
    output: true
  programming:
    defaults:
      layout: post
    permalink: /:collection/:year/:title/
    output: true
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true
```
7.run
 bundle exec jekyll serve 
 
 
after these steps
I can get another blog named programming, but it's content is same with blog

when I set pagination enable to false in programming.md, I can get right content but without pages

so how can I do to create multi blogs, each blog has different tags and different folder?

you can see all the code in repo:
https://github.com/DamonsJ/multi-language-al-folio/tree/bookshelf-v2

and commit :

https://github.com/george-gca/multi-language-al-folio/compare/bookshelf-v2...DamonsJ:multi-language-al-folio:bookshelf-v2

Thanks!

**Comment by george-gca** [comment]
Just so you know, I just updated `al-folio` with the `jekyll-archives-v2` and bookshelf page, so it is easier for someone to create its own collection. I will later today replicate the code here. I will answer your question there, since someone that is not using the translated version might benefit from it.

**Reply by DamonsJ** [reply]
as you say, I did not replace _posts_ in programming.md and the posts can render correctly.
but the blog name and discriptions and tags did not display correctly. it always show **blog**'s name and tags

**Reply by DamonsJ** [reply]
I create a programming.liquid :
```
<!doctype html>
<html lang="{{ site.lang }}">
  <!-- Head -->
  <head>
    {% if page.redirect %}
      {% if page.redirect == true %}
        {% assign redirect = site.baseurl | append: '/' %}
      {% elsif page.redirect contains '://' %}
        {% assign redirect = page.redirect %}
      {% else %}
        {% assign redirect = page.redirect | relative_url %}
      {% endif %}
      <meta http-equiv="refresh" content="3; url={{ redirect }}">
    {% endif %}
    {% include head.liquid %}
  </head>

  <!-- Body -->
  <body class="{% if site.navbar_fixed %}fixed-top-nav{% endif %} {% unless site.footer_fixed %}sticky-bottom-footer{% endunless %}">
    <!-- Header -->
    {% include header.liquid %}

    <!-- Content2 -->
    {{ content }}

    <!-- Footer -->
    {% include footer.liquid %}

    <!-- JavaScripts -->
    {% include scripts.liquid %}
  </body>
</html>

```

and programming.md

```
---
layout: programming
permalink: /programming/
title: programming
nav: true
nav_order: 3
pagination:
  enabled: true
  collection: programming
  permalink: /page/:num/
  per_page: 5
  sort_field: date
  sort_reverse: true
  trail:
    before: 1 # The number of links before the current page
    after: 3 # The number of links after the current page
---

# Welcome to My Programming Page

<div class="post">
  <div class="header-bar">
    <h2>The number of links after the current page</h2>
    <h2>{{site.blog_name}}</h2>
  </div>
</div>
```

and the result is 

![image](https://github.com/user-attachments/assets/ab520687-1a45-4bb8-9af1-1e3895daa7f8)

it seems _{{ content }}_ always refer blog's content

**Reply by george-gca** [reply]
Your repo above is not updated, for instance it doesn't have the `programming.liquid` file.

But check your `programming.md` above, it has:

```html
 <h2>{{site.blog_name}}</h2>
```

which is exactly the `al-folio` part in the page.

This is handled in our code here:

https://github.com/george-gca/multi-language-al-folio/blob/d41233f48a5419fbbd1789a058b89d17120fc3bf/_pages/en-us/blog.md?plain=1#L6-L7

Your code is not based on the multi-language version I believe.

**Reply by DamonsJ** [reply]
@george-gca 
I have pushed all the code in the [bookshelf-v2](https://github.com/DamonsJ/multi-language-al-folio/tree/bookshelf-v2) branch

I forked bookshelf-v2 branch  not the main.

Anyway, like I said, the _programming_'s content always display _blog_'s content

please help me and check out ! 

Thanks for your help

**Reply by DamonsJ** [reply]
so far, it goes well if I set **pagination enabled**  to false .

if I set enable to true, posts will display right, but blog name and description is not right

```
---
layout: programming
permalink: /programming/
title: programming
blog_name2: programming
description2: programming for academics
nav: true
nav_order: 4
pagination:
  enabled: false
  collection: programming
  permalink: /page/:num/
  per_page: 5
  sort_field: date
  sort_reverse: true
  trail:
    before: 1 # The number of links before the current page
    after: 3 # The number of links after the current page
---
```
